
---
namespace: production
# namePrefix: prod-
resources:
  - ../base
  - namespace.yaml
secretGenerator:
  - name: db-name
    literals:
    - db-name=./dev.sqlite
  - name: db-user
    literals:
    - db-user=user 
  - name: db-pwd
    literals:
    - db-pwd=password 